[package]
name = "tissue"
version = "0.1.0"
edition = "2021"
exclude = ["./examples/*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
regex = "^1.10.4"
